# == Schema Information
#
# Table name: food_forecast_mst_food_components
#
#  id          :integer          not null, primary key
#  mst_food_id :integer          not null
#  factor      :integer          not null
#  value       :float(24)        default(0.0), not null
#
# Indexes
#
#  food_components_food_factor_index  (mst_food_id,factor)
#

class FoodForecast::MstFoodComponent < ApplicationRecord
  enum factor: [
    :moisture,
    :protein,
    :fat,
    :saturated_fatty_acid,
    :ash,
    :carbohydrate,
    :dietary_fiber,
    :sugar_content,
    :glucose,
    :fructose,
    :half_lactose,
    :maltose,
    :sucrose,
    :lactose,
    :sodium,
    :potassium,
    :calcium,
    :magnesium,
    :iron,
    :zinc,
    :rin,
    :copper,
    :vitaminA,
    :retinol_active,
    :a_carotene,
    :b_carotene,
    :retinol,
    :a_tocopherol_equivalent,
    :vitaminE,
    :a_tocopherol,
    :b_tocopherol,
    :y_tocopherol,
    :d_tocopherol,
    :vitamin_b1,
    :vitamin_b2,
    :niacin,
    :vitaminB6,
    :vitaminB12,
    :folic_acid,
    :vitaminC,
    :fatty_acidS,
    :butyric_acid_ingredient_value,
    :hexanoic_acid_component_value,
    :bitterness_ingredient_value,
    :capric_acid_component_value,
    :lauric_acid_component_value,
    :tridecanoic_acid_ingredient_value,
    :myristic_acid_ingredient_value,
    :pentadecanoic_acid_component_value,
    :palmitic_acid_ingredient_value,
    :hexadecanoic_acid_ingredient_value,
    :stearic_acid_ingredient_value,
    :decanoic_acid_ingredient_value,
    :amino_acid_ingredient_value,
    :mountain_acid_ingredient_value,
    :hydroxylic_acid_ingredient_value,
    :fatty_acidM_ingredient_value,
    :myristic_acid2_ingredient_value,
    :palmitoleic_acid_component_values,
    :oleic_acid_component_value,
    :codic_acid_ingredient_value,
    :erucic_acid_ingredient_value,
    :fatty_acid_P_ingredient_value,
    :linoleic_acid_ingredient_value,
    :sub_linoleic_acid_ingredient_value,
    :octadecatetraenoic_acid_component_value,
    :peanutoleic_acid_ingredient_value,
    :eicosapentaenoic_acid_component_value,
    :dodecaenoic_acid_ingredient_value,
    :hydrochloric_acid_ingredient_value,
    :other_fatty_acid_ingredient_value,
    :unsaturated_fatty_acid,
    :hydrolyzed_amino_acids_ingredient_value,
    :aspartic_acid_component_value,
    :fumaric_acid_component_value,
    :serine_component_value,
    :glutamic_acid_component_value,
    :proline_ingredient_value,
    :glycine_component_value,
    :alanine_component_value,
    :cysteic_acid_component_value,
    :valine_acid_component_value,
    :methionine_component_value,
    :isoleucine_component_value,
    :leucine_component_value,
    :tyrosine_component_value,
    :phenylalanine_component_value,
    :lysine_component_value,
    :histidine_component_value,
    :arginine_component_value,
    :tryptophan_component_value,
    :cholesterol,
    :alcohol
  ]

  FACTOR_WORDS = {
    moisture: "水分",
    protein: "粗タンパク",
    fat: "粗脂肪",
    saturated_fatty_acid: "飽和脂肪酸",
    ash: "灰分",
    carbohydrate: "総炭水化物",
    dietary_fiber: "食物繊維",
    sugar_content: "糖質の総量",
    glucose: "ブドウ糖",
    fructose: "果糖",
    half_lactose: "半乳糖",
    maltose: "麦芽糖",
    sucrose: "蔗糖",
    lactose: "乳糖",
    sodium: "ナトリウム",
    potassium: "カリウム",
    calcium: "カルシウム",
    magnesium: "マグネシウム",
    iron: "鉄",
    zinc: "亜鉛",
    rin: "リン",
    copper: "銅",
    vitaminA: "ビタミンA総量",
    retinol_active: "レチノール活性当量",
    a_carotene: "α-カロテン",
    b_carotene: "β-カロテン",
    retinol: "レチノール",
    a_tocopherol_equivalent: "α-トコフェロール当量",
    vitaminE: "ビタミンE総量",
    a_tocopherol: "α-トコフェロール",
    b_tocopherol: "β-トコフェロール",
    y_tocopherol: "γ-トコフェロール",
    d_tocopherol: "δ-トコフェロール",
    vitamin_b1: "ビタミンB1",
    vitamin_b2: "ビタミンB2",
    niacin: "ナイアシン",
    vitaminB6: "ビタミンB6",
    vitaminB12: "ビタミンB12",
    folic_acid: "葉酸",
    vitaminC: "ビタミンC",
    fatty_acidS: "脂肪酸S総量",
    butyric_acid_ingredient_value: "酪酸-成分值",
    hexanoic_acid_component_value: "己酸-成分值",
    bitterness_ingredient_value: "辛酸(8:0)-成分值",
    capric_acid_component_value: "癸酸-成分值",
    lauric_acid_component_value: "月桂酸-成分值",
    tridecanoic_acid_ingredient_value: "十三酸-成分值",
    myristic_acid_ingredient_value: "肉豆蔻酸-成分值",
    pentadecanoic_acid_component_value: "十五酸-成分值",
    palmitic_acid_ingredient_value: "棕櫚酸-成分值",
    hexadecanoic_acid_ingredient_value: "十七酸-成分值",
    stearic_acid_ingredient_value: "硬脂酸-成分值",
    decanoic_acid_ingredient_value: "十九酸-成分值",
    amino_acid_ingredient_value: "花生酸-成分值",
    mountain_acid_ingredient_value: "山酸-成分值",
    hydroxylic_acid_ingredient_value: "廿四酸-成分值",
    fatty_acidM_ingredient_value: "脂肪酸M總量-成分值",
    myristic_acid2_ingredient_value: "肉豆蔻烯酸-成分值",
    palmitoleic_acid_component_values: "棕櫚烯酸-成分值",
    oleic_acid_component_value: "油酸-成分值",
    codic_acid_ingredient_value: "鱈烯酸-成分值",
    erucic_acid_ingredient_value: "芥子酸-成分值",
    fatty_acid_P_ingredient_value: "脂肪酸P總量-成分值",
    linoleic_acid_ingredient_value: "亞麻油酸-成分值",
    sub_linoleic_acid_ingredient_value: "次亞麻油酸-成分值",
    octadecatetraenoic_acid_component_value: "十八碳四烯酸-成分值",
    peanutoleic_acid_ingredient_value: "花生油酸-成分值",
    eicosapentaenoic_acid_component_value: "廿碳五烯酸-成分值",
    dodecaenoic_acid_ingredient_value: "廿二碳五烯酸-成分值",
    hydrochloric_acid_ingredient_value: "廿二碳六烯酸-成分值",
    other_fatty_acid_ingredient_value: "其他脂肪酸-成分值",
    unsaturated_fatty_acid: "不飽和脂肪酸",
    hydrolyzed_amino_acids_ingredient_value: "水解胺基酸總量-成分值",
    aspartic_acid_component_value: "天門冬胺酸(Asp)-成分值",
    fumaric_acid_component_value: "酥胺酸(Thr)-成分值",
    serine_component_value: "絲胺酸(Ser)-成分值",
    glutamic_acid_component_value: "麩胺酸(Glu)-成分值",
    proline_ingredient_value: "脯胺酸(Pro)-成分值",
    glycine_component_value: "甘胺酸(Gly)-成分值",
    alanine_component_value: "丙胺酸(Ala)-成分值",
    cysteic_acid_component_value: "胱胺酸(Cys)-成分值",
    valine_acid_component_value: "纈胺酸(Val)-成分值",
    methionine_component_value: "甲硫胺酸(Met)-成分值",
    isoleucine_component_value: "異白胺酸(Ile)-成分值",
    leucine_component_value: "白胺酸(Leu)-成分值",
    tyrosine_component_value: "酪胺酸(Tyr)-成分值",
    phenylalanine_component_value: "苯丙胺酸(Phe)-成分值",
    lysine_component_value: "離胺酸(Lys)-成分值",
    histidine_component_value: "組胺酸(His)-成分值",
    arginine_component_value: "精胺酸(Arg)-成分值",
    tryptophan_component_value: "色胺酸(Trp)-成分值",
    cholesterol: "コレステロール",
    alcohol: "アルコール"
  }

  belongs_to :food, class_name: 'FoodForecast::MstFood', foreign_key: :mst_food_id, required: false
end
