source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.1'
# Use sqlite3 as the database for Active Record
gem 'mysql2'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

gem 'annotate'
gem 'kaminari'
gem 'activerecord-import'
gem 'devise'
gem 'tweetstream'
gem 'twitter', '>= 6.0.0'
gem 'natto'
gem 'charwidth'

gem 'httpclient'

#お手軽メンテナンスモード
gem 'turnout'

#エクセル操作
gem 'roo'

gem 'facebook-messenger'
gem 'aws-sdk', '~> 2'
gem 'aws-sdk-rails'
gem 'aws-record', '~> 1.0'

gem 'whenever', :require => false

gem 'addressable'
gem 'line-bot-api'
gem "koala", '~> 2.2'
gem 'google-api-client', '~> 0.9'
gem 'youtube-dl.rb'

gem 'omniauth'
gem 'omniauth-twitter'
gem 'omniauth-facebook'
gem 'omniauth-google-oauth2'
gem 'omniauth-instagram'

gem 'wp2txt'

gem 'eventmachine'
gem 'faye-websocket'
gem "timers"

gem 'rails-i18n', '~> 5.0.0'

gem 'activeadmin', git: 'https://github.com/activeadmin/activeadmin'
gem 'inherited_resources', git: 'https://github.com/activeadmin/inherited_resources'

gem 'cabocha'
gem 'xml-simple'
gem 'fastimage'

gem 'puma_worker_killer'

gem 'geocoder'

gem 'opengraph_parser'
gem 'canonical-rails', github: 'jumph4x/canonical-rails'
gem 'foreman'

gem 'qiita'
gem 'slideshare_api'
gem 'useragent'

gem 'romaji'
gem 'flickraw'
gem 'rack-cors', :require => 'rack/cors'
gem 'mini_magick'
gem 'sidekiq'
gem 'redis-namespace'
gem 'cairo'
gem 'omniauth-spotify'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'capistrano'
  gem 'capistrano-rails'
  gem 'capistrano-rvm'
  gem 'capistrano-bundler'
  gem 'capistrano3-puma'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
