source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.1'
# Use sqlite3 as the database for Active Record
gem 'mysql2'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

gem 'annotate'
gem 'kaminari'
gem 'activerecord-import'
gem 'devise'
gem 'tweetstream'
gem 'twitter', '>= 6.0.0'
gem 'natto'
gem 'charwidth'

gem 'httpclient'

#お手軽メンテナンスモード
gem 'turnout'

#エクセル操作
gem 'roo'

gem 'aws-sdk', '~> 2'
gem 'aws-sdk-rails'

gem 'whenever', :require => false

gem 'addressable'
gem 'google-api-client'
gem 'google_drive'

gem 'omniauth'
gem 'omniauth-twitter'
gem 'omniauth-facebook'
gem 'omniauth-google-oauth2'

gem 'rails-i18n'

gem 'activeadmin', git: 'https://github.com/activeadmin/activeadmin'
gem 'inherited_resources', git: 'https://github.com/activeadmin/inherited_resources'
gem 'active_admin_import', git: 'https://github.com/activeadmin-plugins/active_admin_import'

gem 'xml-simple'
gem 'fastimage'

gem 'puma_worker_killer'

gem 'geocoder'

gem 'opengraph_parser'
gem 'canonical-rails', github: 'jumph4x/canonical-rails'
gem 'foreman'

gem 'qiita'
gem 'slideshare_api'
gem 'useragent'

gem 'flickraw'
gem 'mini_magick'
gem 'sidekiq'
gem 'redis-namespace'
gem 'omniauth-spotify'
gem 'pdf-reader'
gem 'twilio-ruby'

gem 'dotenv-rails', require: 'dotenv/rails-now'
gem 'geokit-rails'
gem 'webpacker'

#gem 'rack-cors', :require => 'rack/cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
