<?xml version="1.0" encoding="UTF-8" ?>
<Package name="Citore" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="behavior_1" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="__init__" src="lib/requests/__init__.py" />
        <File name="__init__" src="lib/requests/__init__.pyc" />
        <File name="_internal_utils" src="lib/requests/_internal_utils.py" />
        <File name="_internal_utils" src="lib/requests/_internal_utils.pyc" />
        <File name="adapters" src="lib/requests/adapters.py" />
        <File name="adapters" src="lib/requests/adapters.pyc" />
        <File name="api" src="lib/requests/api.py" />
        <File name="api" src="lib/requests/api.pyc" />
        <File name="auth" src="lib/requests/auth.py" />
        <File name="auth" src="lib/requests/auth.pyc" />
        <File name="cacert" src="lib/requests/cacert.pem" />
        <File name="certs" src="lib/requests/certs.py" />
        <File name="certs" src="lib/requests/certs.pyc" />
        <File name="compat" src="lib/requests/compat.py" />
        <File name="compat" src="lib/requests/compat.pyc" />
        <File name="cookies" src="lib/requests/cookies.py" />
        <File name="cookies" src="lib/requests/cookies.pyc" />
        <File name="exceptions" src="lib/requests/exceptions.py" />
        <File name="exceptions" src="lib/requests/exceptions.pyc" />
        <File name="hooks" src="lib/requests/hooks.py" />
        <File name="hooks" src="lib/requests/hooks.pyc" />
        <File name="models" src="lib/requests/models.py" />
        <File name="models" src="lib/requests/models.pyc" />
        <File name="__init__" src="lib/requests/packages/__init__.py" />
        <File name="__init__" src="lib/requests/packages/__init__.pyc" />
        <File name="__init__" src="lib/requests/packages/chardet/__init__.py" />
        <File name="__init__" src="lib/requests/packages/chardet/__init__.pyc" />
        <File name="big5freq" src="lib/requests/packages/chardet/big5freq.py" />
        <File name="big5freq" src="lib/requests/packages/chardet/big5freq.pyc" />
        <File name="big5prober" src="lib/requests/packages/chardet/big5prober.py" />
        <File name="big5prober" src="lib/requests/packages/chardet/big5prober.pyc" />
        <File name="chardetect" src="lib/requests/packages/chardet/chardetect.py" />
        <File name="chardetect" src="lib/requests/packages/chardet/chardetect.pyc" />
        <File name="chardistribution" src="lib/requests/packages/chardet/chardistribution.py" />
        <File name="chardistribution" src="lib/requests/packages/chardet/chardistribution.pyc" />
        <File name="charsetgroupprober" src="lib/requests/packages/chardet/charsetgroupprober.py" />
        <File name="charsetgroupprober" src="lib/requests/packages/chardet/charsetgroupprober.pyc" />
        <File name="charsetprober" src="lib/requests/packages/chardet/charsetprober.py" />
        <File name="charsetprober" src="lib/requests/packages/chardet/charsetprober.pyc" />
        <File name="codingstatemachine" src="lib/requests/packages/chardet/codingstatemachine.py" />
        <File name="codingstatemachine" src="lib/requests/packages/chardet/codingstatemachine.pyc" />
        <File name="compat" src="lib/requests/packages/chardet/compat.py" />
        <File name="compat" src="lib/requests/packages/chardet/compat.pyc" />
        <File name="constants" src="lib/requests/packages/chardet/constants.py" />
        <File name="constants" src="lib/requests/packages/chardet/constants.pyc" />
        <File name="cp949prober" src="lib/requests/packages/chardet/cp949prober.py" />
        <File name="cp949prober" src="lib/requests/packages/chardet/cp949prober.pyc" />
        <File name="escprober" src="lib/requests/packages/chardet/escprober.py" />
        <File name="escprober" src="lib/requests/packages/chardet/escprober.pyc" />
        <File name="escsm" src="lib/requests/packages/chardet/escsm.py" />
        <File name="escsm" src="lib/requests/packages/chardet/escsm.pyc" />
        <File name="eucjpprober" src="lib/requests/packages/chardet/eucjpprober.py" />
        <File name="eucjpprober" src="lib/requests/packages/chardet/eucjpprober.pyc" />
        <File name="euckrfreq" src="lib/requests/packages/chardet/euckrfreq.py" />
        <File name="euckrfreq" src="lib/requests/packages/chardet/euckrfreq.pyc" />
        <File name="euckrprober" src="lib/requests/packages/chardet/euckrprober.py" />
        <File name="euckrprober" src="lib/requests/packages/chardet/euckrprober.pyc" />
        <File name="euctwfreq" src="lib/requests/packages/chardet/euctwfreq.py" />
        <File name="euctwfreq" src="lib/requests/packages/chardet/euctwfreq.pyc" />
        <File name="euctwprober" src="lib/requests/packages/chardet/euctwprober.py" />
        <File name="euctwprober" src="lib/requests/packages/chardet/euctwprober.pyc" />
        <File name="gb2312freq" src="lib/requests/packages/chardet/gb2312freq.py" />
        <File name="gb2312freq" src="lib/requests/packages/chardet/gb2312freq.pyc" />
        <File name="gb2312prober" src="lib/requests/packages/chardet/gb2312prober.py" />
        <File name="gb2312prober" src="lib/requests/packages/chardet/gb2312prober.pyc" />
        <File name="hebrewprober" src="lib/requests/packages/chardet/hebrewprober.py" />
        <File name="hebrewprober" src="lib/requests/packages/chardet/hebrewprober.pyc" />
        <File name="jisfreq" src="lib/requests/packages/chardet/jisfreq.py" />
        <File name="jisfreq" src="lib/requests/packages/chardet/jisfreq.pyc" />
        <File name="jpcntx" src="lib/requests/packages/chardet/jpcntx.py" />
        <File name="jpcntx" src="lib/requests/packages/chardet/jpcntx.pyc" />
        <File name="langbulgarianmodel" src="lib/requests/packages/chardet/langbulgarianmodel.py" />
        <File name="langbulgarianmodel" src="lib/requests/packages/chardet/langbulgarianmodel.pyc" />
        <File name="langcyrillicmodel" src="lib/requests/packages/chardet/langcyrillicmodel.py" />
        <File name="langcyrillicmodel" src="lib/requests/packages/chardet/langcyrillicmodel.pyc" />
        <File name="langgreekmodel" src="lib/requests/packages/chardet/langgreekmodel.py" />
        <File name="langgreekmodel" src="lib/requests/packages/chardet/langgreekmodel.pyc" />
        <File name="langhebrewmodel" src="lib/requests/packages/chardet/langhebrewmodel.py" />
        <File name="langhebrewmodel" src="lib/requests/packages/chardet/langhebrewmodel.pyc" />
        <File name="langhungarianmodel" src="lib/requests/packages/chardet/langhungarianmodel.py" />
        <File name="langhungarianmodel" src="lib/requests/packages/chardet/langhungarianmodel.pyc" />
        <File name="langthaimodel" src="lib/requests/packages/chardet/langthaimodel.py" />
        <File name="langthaimodel" src="lib/requests/packages/chardet/langthaimodel.pyc" />
        <File name="latin1prober" src="lib/requests/packages/chardet/latin1prober.py" />
        <File name="latin1prober" src="lib/requests/packages/chardet/latin1prober.pyc" />
        <File name="mbcharsetprober" src="lib/requests/packages/chardet/mbcharsetprober.py" />
        <File name="mbcharsetprober" src="lib/requests/packages/chardet/mbcharsetprober.pyc" />
        <File name="mbcsgroupprober" src="lib/requests/packages/chardet/mbcsgroupprober.py" />
        <File name="mbcsgroupprober" src="lib/requests/packages/chardet/mbcsgroupprober.pyc" />
        <File name="mbcssm" src="lib/requests/packages/chardet/mbcssm.py" />
        <File name="mbcssm" src="lib/requests/packages/chardet/mbcssm.pyc" />
        <File name="sbcharsetprober" src="lib/requests/packages/chardet/sbcharsetprober.py" />
        <File name="sbcharsetprober" src="lib/requests/packages/chardet/sbcharsetprober.pyc" />
        <File name="sbcsgroupprober" src="lib/requests/packages/chardet/sbcsgroupprober.py" />
        <File name="sbcsgroupprober" src="lib/requests/packages/chardet/sbcsgroupprober.pyc" />
        <File name="sjisprober" src="lib/requests/packages/chardet/sjisprober.py" />
        <File name="sjisprober" src="lib/requests/packages/chardet/sjisprober.pyc" />
        <File name="universaldetector" src="lib/requests/packages/chardet/universaldetector.py" />
        <File name="universaldetector" src="lib/requests/packages/chardet/universaldetector.pyc" />
        <File name="utf8prober" src="lib/requests/packages/chardet/utf8prober.py" />
        <File name="utf8prober" src="lib/requests/packages/chardet/utf8prober.pyc" />
        <File name="__init__" src="lib/requests/packages/idna/__init__.py" />
        <File name="__init__" src="lib/requests/packages/idna/__init__.pyc" />
        <File name="codec" src="lib/requests/packages/idna/codec.py" />
        <File name="codec" src="lib/requests/packages/idna/codec.pyc" />
        <File name="compat" src="lib/requests/packages/idna/compat.py" />
        <File name="compat" src="lib/requests/packages/idna/compat.pyc" />
        <File name="core" src="lib/requests/packages/idna/core.py" />
        <File name="core" src="lib/requests/packages/idna/core.pyc" />
        <File name="idnadata" src="lib/requests/packages/idna/idnadata.py" />
        <File name="idnadata" src="lib/requests/packages/idna/idnadata.pyc" />
        <File name="intranges" src="lib/requests/packages/idna/intranges.py" />
        <File name="intranges" src="lib/requests/packages/idna/intranges.pyc" />
        <File name="uts46data" src="lib/requests/packages/idna/uts46data.py" />
        <File name="uts46data" src="lib/requests/packages/idna/uts46data.pyc" />
        <File name="__init__" src="lib/requests/packages/urllib3/__init__.py" />
        <File name="__init__" src="lib/requests/packages/urllib3/__init__.pyc" />
        <File name="_collections" src="lib/requests/packages/urllib3/_collections.py" />
        <File name="_collections" src="lib/requests/packages/urllib3/_collections.pyc" />
        <File name="connection" src="lib/requests/packages/urllib3/connection.py" />
        <File name="connection" src="lib/requests/packages/urllib3/connection.pyc" />
        <File name="connectionpool" src="lib/requests/packages/urllib3/connectionpool.py" />
        <File name="connectionpool" src="lib/requests/packages/urllib3/connectionpool.pyc" />
        <File name="__init__" src="lib/requests/packages/urllib3/contrib/__init__.py" />
        <File name="__init__" src="lib/requests/packages/urllib3/contrib/__init__.pyc" />
        <File name="appengine" src="lib/requests/packages/urllib3/contrib/appengine.py" />
        <File name="appengine" src="lib/requests/packages/urllib3/contrib/appengine.pyc" />
        <File name="ntlmpool" src="lib/requests/packages/urllib3/contrib/ntlmpool.py" />
        <File name="ntlmpool" src="lib/requests/packages/urllib3/contrib/ntlmpool.pyc" />
        <File name="pyopenssl" src="lib/requests/packages/urllib3/contrib/pyopenssl.py" />
        <File name="pyopenssl" src="lib/requests/packages/urllib3/contrib/pyopenssl.pyc" />
        <File name="socks" src="lib/requests/packages/urllib3/contrib/socks.py" />
        <File name="socks" src="lib/requests/packages/urllib3/contrib/socks.pyc" />
        <File name="exceptions" src="lib/requests/packages/urllib3/exceptions.py" />
        <File name="exceptions" src="lib/requests/packages/urllib3/exceptions.pyc" />
        <File name="fields" src="lib/requests/packages/urllib3/fields.py" />
        <File name="fields" src="lib/requests/packages/urllib3/fields.pyc" />
        <File name="filepost" src="lib/requests/packages/urllib3/filepost.py" />
        <File name="filepost" src="lib/requests/packages/urllib3/filepost.pyc" />
        <File name="__init__" src="lib/requests/packages/urllib3/packages/__init__.py" />
        <File name="__init__" src="lib/requests/packages/urllib3/packages/__init__.pyc" />
        <File name="__init__" src="lib/requests/packages/urllib3/packages/backports/__init__.py" />
        <File name="__init__" src="lib/requests/packages/urllib3/packages/backports/__init__.pyc" />
        <File name="makefile" src="lib/requests/packages/urllib3/packages/backports/makefile.py" />
        <File name="makefile" src="lib/requests/packages/urllib3/packages/backports/makefile.pyc" />
        <File name="ordered_dict" src="lib/requests/packages/urllib3/packages/ordered_dict.py" />
        <File name="ordered_dict" src="lib/requests/packages/urllib3/packages/ordered_dict.pyc" />
        <File name="six" src="lib/requests/packages/urllib3/packages/six.py" />
        <File name="six" src="lib/requests/packages/urllib3/packages/six.pyc" />
        <File name="__init__" src="lib/requests/packages/urllib3/packages/ssl_match_hostname/__init__.py" />
        <File name="__init__" src="lib/requests/packages/urllib3/packages/ssl_match_hostname/__init__.pyc" />
        <File name="_implementation" src="lib/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.py" />
        <File name="_implementation" src="lib/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.pyc" />
        <File name="poolmanager" src="lib/requests/packages/urllib3/poolmanager.py" />
        <File name="poolmanager" src="lib/requests/packages/urllib3/poolmanager.pyc" />
        <File name="request" src="lib/requests/packages/urllib3/request.py" />
        <File name="request" src="lib/requests/packages/urllib3/request.pyc" />
        <File name="response" src="lib/requests/packages/urllib3/response.py" />
        <File name="response" src="lib/requests/packages/urllib3/response.pyc" />
        <File name="__init__" src="lib/requests/packages/urllib3/util/__init__.py" />
        <File name="__init__" src="lib/requests/packages/urllib3/util/__init__.pyc" />
        <File name="connection" src="lib/requests/packages/urllib3/util/connection.py" />
        <File name="connection" src="lib/requests/packages/urllib3/util/connection.pyc" />
        <File name="request" src="lib/requests/packages/urllib3/util/request.py" />
        <File name="request" src="lib/requests/packages/urllib3/util/request.pyc" />
        <File name="response" src="lib/requests/packages/urllib3/util/response.py" />
        <File name="response" src="lib/requests/packages/urllib3/util/response.pyc" />
        <File name="retry" src="lib/requests/packages/urllib3/util/retry.py" />
        <File name="retry" src="lib/requests/packages/urllib3/util/retry.pyc" />
        <File name="ssl_" src="lib/requests/packages/urllib3/util/ssl_.py" />
        <File name="ssl_" src="lib/requests/packages/urllib3/util/ssl_.pyc" />
        <File name="timeout" src="lib/requests/packages/urllib3/util/timeout.py" />
        <File name="timeout" src="lib/requests/packages/urllib3/util/timeout.pyc" />
        <File name="url" src="lib/requests/packages/urllib3/util/url.py" />
        <File name="url" src="lib/requests/packages/urllib3/util/url.pyc" />
        <File name="sessions" src="lib/requests/sessions.py" />
        <File name="sessions" src="lib/requests/sessions.pyc" />
        <File name="status_codes" src="lib/requests/status_codes.py" />
        <File name="status_codes" src="lib/requests/status_codes.pyc" />
        <File name="structures" src="lib/requests/structures.py" />
        <File name="structures" src="lib/requests/structures.pyc" />
        <File name="utils" src="lib/requests/utils.py" />
        <File name="utils" src="lib/requests/utils.pyc" />
    </Resources>
    <Topics />
    <IgnoredPaths>
        <Path src=".metadata" />
    </IgnoredPaths>
</Package>
